name: Version Bump on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine version bump type
        id: bump_type
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          # Check PR title/body for version bump hints
          if echo "$PR_TITLE $PR_BODY" | grep -iE '(breaking|major)'; then
            echo "type=major" >> $GITHUB_OUTPUT
          elif echo "$PR_TITLE $PR_BODY" | grep -iE '(feat|feature|minor)'; then
            echo "type=minor" >> $GITHUB_OUTPUT
          else
            echo "type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        run: |
          npm version ${{ steps.bump_type.outputs.type }} -m "chore: bump version to %s [skip ci]"

      - name: Push changes
        run: |
          git push origin main --follow-tags
